name: Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        FLAVOR=virt ./docker-build.sh
        FLAVOR=lts ./docker-build.sh
        ls -hl dist

    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        sudo snap install hub --classic
        build_date=$(date +%Y%m%d)
        build_number=$[$(git tag | grep $build_date | wc -l) + 1]
        tag="$build_date.$build_number"
        hub release create $tag -m "$tag" -a dist/*.gz
